import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import RecoilRootProvider from "@/components/provider/RecoilRootProvider";
import clsx from "clsx";
import GlobalPageLayout from "@/components/layout/GlobalPage.layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "flex justify-center")}>
        <RecoilRootProvider>
          <GlobalPageLayout>{children}</GlobalPageLayout>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
